# 服务端口
server:
  port: 8081

spring:
  # 服务名称
  application:
    name: springboot-mybatis-plus
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  # thymeleaf热更新
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     mode: HTML
     encoding: UTF-8
     suffix: .html
# mybatis-plus相关配置
mybatis-plus:
  # entity扫描
  type-aliases-package: com.wode.springbootmybatisplus.entity
  global-config:
    db-config:
      # AUTO -> 数据库ID自增
      # INPUT -> 用户输入ID
      # ID_WORKER -> 全局唯一ID（数字类型唯一ID）
      # UUID -> 全局唯一ID（UUID）
      id-type: UUID
      # 全局表前缀
      table-prefix: tb_